# Generated by Django 2.2.2 on 2019-07-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scouts', '0025_auto_20190731_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOutSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scouts.ScoutSubTaskCategory')),
                ('parent_task', models.ForeignKey(default='Move Out', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scouts.ScoutTaskCategory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='MoveOutRemark',
            fields=[
                ('moveoutsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.MoveOutSubTask')),
                ('content', models.TextField(blank=True, null=True)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_out_remark', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.moveoutsubtask',),
        ),
        migrations.CreateModel(
            name='MoveOutAmenitiesCheckup',
            fields=[
                ('moveoutsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.MoveOutSubTask')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_out_amenity_checkup', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.moveoutsubtask',),
        ),
    ]
