# Generated by Django 2.2.2 on 2019-07-31 10:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0002_auto_20190731_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveoutamenitiescheckup',
            name='amenities_json',
            field=jsonfield.fields.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
