# Generated by Django 2.2.2 on 2019-07-31 10:34

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0003_moveoutamenitiescheckup_amenities_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveoutamenitiescheckup',
            name='amenities_json',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
