# Generated by Django 2.2.2 on 2019-07-31 11:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0004_auto_20190731_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveoutamenitiescheckup',
            name='amenities_json',
            field=jsonfield.fields.JSONField(default={'data': {'amenities_dict': {}}}),
        ),
    ]
