# Generated by Django 2.2.2 on 2019-08-02 11:51

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import multiselectfield.db.fields
import scouts.sub_tasks.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0027_auto_20190802_1409'),
        ('sub_tasks', '0005_auto_20190731_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOnBoardingSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_subtask_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scouts.ScoutSubTaskCategory')),
                ('parent_task_category', models.ForeignKey(default='Property Onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scouts.ScoutTaskCategory', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOnBoardingHousePhoto',
            fields=[
                ('propertyonboardingsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.PropertyOnBoardingSubTask')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_on_board_house_photo', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.propertyonboardingsubtask',),
        ),
        migrations.CreateModel(
            name='PropertyOnBoardingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=scouts.sub_tasks.utils.get_property_on_boarding_house_picture_upload_path)),
                ('property_on_boarding_house_photo_sub_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='sub_tasks.PropertyOnBoardingHousePhoto')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyOnBoardingHouseBasicDetail',
            fields=[
                ('propertyonboardingsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.PropertyOnBoardingSubTask')),
                ('furnish_type', models.CharField(choices=[('full', 'Fully furnished'), ('semi', 'Semi furnished'), ('nil', 'Unfurnished')], max_length=30)),
                ('space_type', multiselectfield.db.fields.MultiSelectField(choices=[('shared', 'Shared rooms'), ('private', 'Private rooms'), ('flat', 'Entire house')], max_length=25)),
                ('rent', models.FloatField()),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_on_board_house_basic_details', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.propertyonboardingsubtask',),
        ),
        migrations.CreateModel(
            name='PropertyOnBoardingHouseAmenity',
            fields=[
                ('propertyonboardingsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.PropertyOnBoardingSubTask')),
                ('amenities_json', jsonfield.fields.JSONField(default={'data': {'amenities_dict': {}}})),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_on_board_house_amenity', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.propertyonboardingsubtask',),
        ),
        migrations.CreateModel(
            name='PropertyOnBoardingHouseAddress',
            fields=[
                ('propertyonboardingsubtask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sub_tasks.PropertyOnBoardingSubTask')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_on_board_house_address', to='scouts.ScoutTask')),
            ],
            bases=('sub_tasks.propertyonboardingsubtask',),
        ),
    ]
