# Generated by Django 2.2.2 on 2019-08-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0007_auto_20190803_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyOnBoardingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='propertyonboardinghousebasicdetail',
            name='bhk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='propertyonboardinghousebasicdetail',
            name='rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
