# Generated by Django 2.2.2 on 2019-08-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0009_auto_20190805_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
