# Generated by Django 2.2.2 on 2019-08-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0010_auto_20190805_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyonboardingdetail',
            old_name='scheduled_time',
            new_name='scheduled_at',
        ),
    ]
