# Generated by Django 2.2.2 on 2019-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_tasks', '0011_auto_20190805_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='phone_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='propertyonboardingdetail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
