# Generated by Django 2.2.2 on 2019-06-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('new_participant_scout', 'New Scout'), ('new_participant_tenant', 'New Tenant')], max_length=30),
        ),
    ]
