# Generated by Django 2.2.2 on 2019-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190612_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
