# Generated by Django 2.2.2 on 2019-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='chat_room_name',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
    ]
