# Generated by Django 2.2.2 on 2019-06-13 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190613_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chat.Conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='chat.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='scout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_participant', to='scouts.Scout'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('participant_scout', 'Scout'), ('participant_customer', 'Customer')], max_length=30),
        ),
    ]
