# Generated by Django 2.2.2 on 2019-06-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(choices=[('scout', 'Scout'), ('customer', 'Customer')], max_length=30),
        ),
    ]
