# Generated by Django 2.2.2 on 2019-06-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20190615_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket_id', models.CharField(max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Participant')),
            ],
        ),
    ]
