# Generated by Django 2.2.2 on 2019-07-30 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20190628_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocketClient',
        ),
    ]
