# Generated by Django 2.2.2 on 2019-06-07 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scouts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='profile_pic_thumbnail_url',
            field=models.CharField(blank=True, default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic_small.jpg', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='scout',
            name='profile_pic_url',
            field=models.CharField(blank=True, default='https://d28fujbigzf56k.cloudfront.net/static/img/nopic.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ScoutWorkAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('same_as_permanent_address', models.BooleanField(default=False)),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_address', to='scouts.Scout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.FloatField(default=0)),
                ('debit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('pending_deposit', models.FloatField(default=0)),
                ('pending_withdrawal', models.FloatField(default=0)),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to='scouts.Scout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=scouts.utils.get_picture_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=scouts.utils.get_thumbnail_upload_path)),
                ('is_profile_pic', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='scouts.Scout')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutPermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('complete_address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='scouts.Scout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScoutPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='scouts.ScoutWallet')),
            ],
        ),
        migrations.CreateModel(
            name='ScoutBankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=300, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=25, null=True)),
                ('scout', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_detail', to='scouts.Scout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
