# Generated by Django 2.2.2 on 2019-06-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0002_auto_20190607_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='profile_pic_thumbnail_url',
            field=models.CharField(blank=True, default='https://d3agek5ajs3os7.cloudfront.net/static/img/nopic_small.jpg', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scout',
            name='profile_pic_url',
            field=models.CharField(blank=True, default='https://d3agek5ajs3os7.cloudfront.net/static/img/nopic.jpg', max_length=500, null=True),
        ),
    ]
