# Generated by Django 2.2.2 on 2019-06-07 10:34

from django.db import migrations, models
import django.db.models.deletion
import scouts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0003_auto_20190607_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('PAN', 'PAN')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=scouts.utils.get_scout_document_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=scouts.utils.get_scout_document_thumbnail_upload_path)),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='scouts.Scout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
