# Generated by Django 2.2.2 on 2019-06-08 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0004_scoutdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ScheduledAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('scout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_availabilities', to='scouts.Scout')),
            ],
        ),
    ]
