# Generated by Django 2.2.2 on 2019-06-10 11:38

from django.db import migrations, models
import django.db.models.deletion
import scouts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0007_scoutnotification_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutSubTaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Scout sub task categories',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='ScoutTaskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=scouts.utils.get_scout_task_category_image_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutTaskReviewTagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ScoutTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.PositiveIntegerField(blank=True, null=True)),
                ('visit_id', models.PositiveIntegerField(blank=True, null=True)),
                ('booking_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default=(('unassigned', 'unassigned'), ('assigned', 'assigned'), ('complete', 'complete')), max_length=50)),
                ('earning', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ManyToManyField(blank=True, to='scouts.Scout')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scouts.ScoutTaskCategory')),
                ('review_tags', models.ManyToManyField(blank=True, to='scouts.ScoutTaskReviewTagCategory')),
                ('scout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scouts.Scout')),
                ('sub_tasks', models.ManyToManyField(blank=True, to='scouts.ScoutSubTaskCategory')),
            ],
        ),
        migrations.AddField(
            model_name='scoutsubtaskcategory',
            name='task_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_task_categories', to='scouts.ScoutTaskCategory'),
        ),
    ]
