# Generated by Django 2.2.2 on 2019-06-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0008_auto_20190610_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scouttaskcategory',
            options={'verbose_name_plural': 'Scout task categories'},
        ),
        migrations.AlterModelOptions(
            name='scouttaskreviewtagcategory',
            options={'verbose_name_plural': 'Scout task review status categories'},
        ),
        migrations.AlterField(
            model_name='scouttask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('assigned', 'assigned'), ('complete', 'complete')], max_length=50),
        ),
    ]
