# Generated by Django 2.2.2 on 2019-06-10 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0009_auto_20190610_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttask',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='scouts.ScoutPayment'),
        ),
        migrations.AlterField(
            model_name='scouttask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('complete', 'Complete')], max_length=50),
        ),
    ]
