# Generated by Django 2.2.2 on 2019-06-13 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0010_auto_20190610_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scout', to=settings.AUTH_USER_MODEL),
        ),
    ]
