# Generated by Django 2.2.2 on 2019-06-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0013_auto_20190620_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttaskassignmentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
