# Generated by Django 2.2.2 on 2019-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0014_scouttaskassignmentrequest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scout',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scout',
            name='review_tags',
            field=models.ManyToManyField(blank=True, related_name='scouts', to='scouts.ScoutTaskReviewTagCategory'),
        ),
        migrations.AlterField(
            model_name='scouttask',
            name='review_tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='scouts.ScoutTaskReviewTagCategory'),
        ),
    ]
