# Generated by Django 2.2.2 on 2019-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0015_auto_20190620_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
