# Generated by Django 2.2.2 on 2019-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0016_auto_20190620_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutpermanentaddress',
            name='latitude',
            field=models.FloatField(blank=True, default=28.7041, null=True),
        ),
        migrations.AlterField(
            model_name='scoutpermanentaddress',
            name='longitude',
            field=models.FloatField(blank=True, default=77.1025, null=True),
        ),
        migrations.AlterField(
            model_name='scoutworkaddress',
            name='latitude',
            field=models.FloatField(blank=True, default=28.7041, null=True),
        ),
        migrations.AlterField(
            model_name='scoutworkaddress',
            name='longitude',
            field=models.FloatField(blank=True, default=77.1025, null=True),
        ),
    ]
