# Generated by Django 2.2.2 on 2019-07-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0017_auto_20190712_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutpermanentaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoutpermanentaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoutworkaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoutworkaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
