# Generated by Django 2.2.2 on 2019-07-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0019_auto_20190715_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttaskcategory',
            name='earning',
            field=models.FloatField(default=0),
        ),
    ]
