# Generated by Django 2.2.2 on 2019-07-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0021_scoutpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttask',
            name='rating_given',
            field=models.BooleanField(default=False),
        ),
    ]
