# Generated by Django 2.2.2 on 2019-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0022_scouttask_rating_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scouttask',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
