# Generated by Django 2.2.2 on 2019-07-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0023_auto_20190719_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttaskassignmentrequest',
            name='auto_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
