# Generated by Django 2.2.2 on 2019-08-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0025_auto_20190731_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttask',
            name='move_out_request',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
