# Generated by Django 2.2.2 on 2019-08-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0026_scouttask_move_out_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scouttask',
            old_name='move_out_request',
            new_name='move_out_request_id',
        ),
    ]
