# Generated by Django 2.2.2 on 2019-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouts', '0028_scouttask_onboarding_property_details_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scouttaskassignmentrequest',
            name='pass_to_another_scout',
            field=models.BooleanField(default=True),
        ),
    ]
