# Generated by Django 2.2.2 on 2019-07-29 10:38

import common.utils
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNotificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.utils.get_notification_category_image_upload_path)),
            ],
            options={
                'verbose_name_plural': 'Customer notification categories',
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('payload', jsonfield.fields.JSONField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('display', models.BooleanField(default=True)),
                ('customer_id', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='customers.CustomerNotificationCategory')),
            ],
            options={
                'ordering': ('-timestamp',),
                'abstract': False,
            },
        ),
    ]
